/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndustriesRouteImport } from './routes/industries'
import { Route as GetQuoteRouteImport } from './routes/get-quote'
import { Route as FreightRatesRouteImport } from './routes/freight-rates'
import { Route as DeliveriesRouteImport } from './routes/deliveries'
import { Route as BranchesRouteImport } from './routes/branches'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesRoute = IndustriesRouteImport.update({
  id: '/industries',
  path: '/industries',
  getParentRoute: () => rootRouteImport,
} as any)
const GetQuoteRoute = GetQuoteRouteImport.update({
  id: '/get-quote',
  path: '/get-quote',
  getParentRoute: () => rootRouteImport,
} as any)
const FreightRatesRoute = FreightRatesRouteImport.update({
  id: '/freight-rates',
  path: '/freight-rates',
  getParentRoute: () => rootRouteImport,
} as any)
const DeliveriesRoute = DeliveriesRouteImport.update({
  id: '/deliveries',
  path: '/deliveries',
  getParentRoute: () => rootRouteImport,
} as any)
const BranchesRoute = BranchesRouteImport.update({
  id: '/branches',
  path: '/branches',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/deliveries': typeof DeliveriesRoute
  '/freight-rates': typeof FreightRatesRoute
  '/get-quote': typeof GetQuoteRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/deliveries': typeof DeliveriesRoute
  '/freight-rates': typeof FreightRatesRoute
  '/get-quote': typeof GetQuoteRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/branches': typeof BranchesRoute
  '/deliveries': typeof DeliveriesRoute
  '/freight-rates': typeof FreightRatesRoute
  '/get-quote': typeof GetQuoteRoute
  '/industries': typeof IndustriesRoute
  '/login': typeof LoginRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/deliveries'
    | '/freight-rates'
    | '/get-quote'
    | '/industries'
    | '/login'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/deliveries'
    | '/freight-rates'
    | '/get-quote'
    | '/industries'
    | '/login'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/branches'
    | '/deliveries'
    | '/freight-rates'
    | '/get-quote'
    | '/industries'
    | '/login'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BranchesRoute: typeof BranchesRoute
  DeliveriesRoute: typeof DeliveriesRoute
  FreightRatesRoute: typeof FreightRatesRoute
  GetQuoteRoute: typeof GetQuoteRoute
  IndustriesRoute: typeof IndustriesRoute
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries': {
      id: '/industries'
      path: '/industries'
      fullPath: '/industries'
      preLoaderRoute: typeof IndustriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/get-quote': {
      id: '/get-quote'
      path: '/get-quote'
      fullPath: '/get-quote'
      preLoaderRoute: typeof GetQuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freight-rates': {
      id: '/freight-rates'
      path: '/freight-rates'
      fullPath: '/freight-rates'
      preLoaderRoute: typeof FreightRatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deliveries': {
      id: '/deliveries'
      path: '/deliveries'
      fullPath: '/deliveries'
      preLoaderRoute: typeof DeliveriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/branches': {
      id: '/branches'
      path: '/branches'
      fullPath: '/branches'
      preLoaderRoute: typeof BranchesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BranchesRoute: BranchesRoute,
  DeliveriesRoute: DeliveriesRoute,
  FreightRatesRoute: FreightRatesRoute,
  GetQuoteRoute: GetQuoteRoute,
  IndustriesRoute: IndustriesRoute,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
